version: "3"
services:
  leaguestats-redis:
    networks:
      - leaguestats-network
    container_name: leaguestats-redis
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - leaguestats-redisData:/data
    restart: always
  leaguestats-postgres:
    networks:
      - leaguestats-network
    container_name: leaguestats-postgres
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=leaguestats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./leaguestats-postgresData:/var/lib/postgresql/data
    restart: always
  api:
    container_name: leaguestats-web
    command: ./wait-for-it.sh leaguestats-postgres:5432 -- ./wait-for-it.sh leaguestats-redis:6379 -- sleep 20 -- node ace migration:run --force -- dumb-init node ace serve --watch --encore-args="--host ${HOST} --port 8080"
    networks:
      - leaguestats-network
    links:
      - leaguestats-redis
      - leaguestats-postgres
    env_file:
      - server/.env
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - '3333:3333'
  web:
    container_name: leaguestats-front
    command: npm run preview
    environment:
      - NODE_ENV=production
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - '8000:8080'
volumes:
  leaguestats-redisData:
  leaguestats-postgresData:
networks:
  leaguestats-network:
    driver: bridge
